"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useParams, useSearchParams } from "next/navigation";
import { request } from "../../../lib/api";

const views=["overview","timeline","evidence","people","disputed","questions","workplace"] as const;
type View=typeof views[number]; type Json=Record<string,unknown>;
type Span={id:string;documentVersionId:string;pageNumber?:number;textStart?:number;textEnd?:number;extractedText:string;parserVersion:string;extractionConfidence?:number};
type Assertion={id:string;subjectReference:string;predicate:string;value:string;assertedBy:string;sourceSpanId?:string;dispute:string;verification:string;supersededByAssertionId?:string;epistemicNotice:string};
type TimelineEvent={id:string;label:string;eventType:string;startTime?:string;endTime?:string;status:string;verification:string;sourceSpanIds:string[]};

export default function MatterWorkspace(){
  const params=useParams<{matterId:string}>(); const search=useSearchParams(); const tenant=search.get("workspace")??"";
  const [view,setView]=useState<View>("overview"); const [data,setData]=useState<Json>({}); const [error,setError]=useState(""); const [selected,setSelected]=useState<Span>(); const [busy,setBusy]=useState(false);
  const base=useMemo(()=>`/workspaces/${tenant}/matters/${params.matterId}`,[tenant,params.matterId]);
  async function load(next:View=view){if(!tenant)return;setBusy(true);try{setData(await request<Json>(`${base}/${next}`));setError("");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  useEffect(()=>{void load(view);},[base,view]);
  async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);try{const accepted=await request<{jobId:string}>(`${base}/evidence`,{method:"POST",body:form});for(let attempt=0;attempt<60;attempt++){const job=await request<{status:number;failureCode?:string}>(`${base}/jobs/${accepted.jobId}`);if(job.status===3){setView("evidence");await load("evidence");return;}if(job.status===4)throw new Error(`Processing failed: ${job.failureCode??"unknown"}`);await new Promise(resolve=>setTimeout(resolve,1000));}throw new Error("Processing is still pending; it can safely resume.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function correct(assertion:Assertion){const value=window.prompt("Corrected attributed value",assertion.value);if(!value)return;try{await request(`${base}/assertions/${assertion.id}/corrections`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({correctedValue:value})});await load(view);}catch(e){setError((e as Error).message);}}
  async function download(){try{const csrfResponse=await fetch("/api/auth/csrf");if(!csrfResponse.ok)throw new Error("Your session is unavailable.");const csrf=await csrfResponse.json();const response=await fetch(`/api${base}/exports`,{method:"POST",headers:{"X-CSRF-TOKEN":csrf.token}});if(!response.ok)throw new Error("Export failed");const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download="casemesh-professional-handover.zip";anchor.click();URL.revokeObjectURL(url);}catch(e){setError((e as Error).message);}}
  const spans=((data.sourceSpans??[]) as Span[]); const assertions=((data.assertions??data.disputedAssertions??[]) as Assertion[]);
  return <main><a href="/matters">← All Matters</a><h1>Matter workspace</h1><p className="notice">Statements remain attributed to their source. CaseMesh does not silently promote an allegation or extracted statement into established fact.</p><nav className="tabs" aria-label="Matter views">{views.map(item=><button key={item} aria-pressed={view===item} onClick={()=>setView(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</nav>{error&&<p role="alert" className="error">{error}</p>}{busy&&<p aria-live="polite">Updating private workspace…</p>}<div className="split"><section aria-live="polite"><ViewContent view={view} data={data} assertions={assertions} spans={spans} select={setSelected} correct={correct}/><section className="card"><h2>Add synthetic evidence</h2><form onSubmit={upload}><label>Evidence file<input name="file" type="file" accept=".txt,.pdf,.docx,.eml,.png,.jpg,.jpeg" required/></label><button disabled={busy}>Upload and process</button></form></section><section className="card" style={{marginTop:16}}><h2>Professional handover</h2><p>Generate a private, evidence-grounded bundle with citations and audit history.</p><button onClick={()=>void download()}>Download export</button></section></section><aside className="card source-panel" aria-label="Source citation detail"><h2>Source citation</h2>{selected?<><p><strong>Document version:</strong> {selected.documentVersionId}</p><p><strong>Locator:</strong> {selected.pageNumber?`page ${selected.pageNumber}`:`characters ${selected.textStart}–${selected.textEnd}`}</p><blockquote>{selected.extractedText}</blockquote><p className="muted">Parser {selected.parserVersion}; extraction confidence {selected.extractionConfidence??"not recorded"}. Extraction confidence is not truth confidence.</p></>:<p>Select a citation to inspect its exact immutable document-version span.</p>}</aside></div></main>;
}

function ViewContent({view,data,assertions,spans,select,correct}:{view:View;data:Json;assertions:Assertion[];spans:Span[];select:(s:Span)=>void;correct:(a:Assertion)=>void}){
  if(view==="evidence"||view==="disputed")return <section><h2>{view==="evidence"?"Evidence and attributed statements":"Disputed statements"}</h2><ul className="list">{assertions.map(a=><li className="card" key={a.id}><p><strong>{a.assertedBy}</strong> asserted: {a.subjectReference} {a.predicate} {a.value}</p><p className="muted">{a.epistemicNotice}</p><div className="row">{a.sourceSpanId&&<button className="citation" onClick={()=>{const span=spans.find(s=>s.id===a.sourceSpanId);if(span)select(span);}}>View source</button>}<button className="secondary" onClick={()=>void correct(a)} disabled={!!a.supersededByAssertionId}>Correct with audit trail</button></div></li>)}</ul>{spans.length>0&&<h3>Exact source spans</h3>}{spans.map(s=><button className="citation" key={s.id} onClick={()=>select(s)}>{s.pageNumber?`Page ${s.pageNumber}`:`Characters ${s.textStart}–${s.textEnd}`}</button>)}</section>;
  if(view==="timeline")return <section><h2>Chronology</h2><ul className="list">{((data.events??[]) as TimelineEvent[]).map(event=><li className="card" key={event.id}><h3>{event.label}</h3><p><strong>Type:</strong> {event.eventType}</p><p><strong>Time:</strong> {event.startTime??"not established"}{event.endTime?` – ${event.endTime}`:""}</p><p><strong>Status:</strong> {event.status}; <strong>verification:</strong> {event.verification}</p><div className="row">{event.sourceSpanIds.map(id=><button className="citation" key={id} onClick={()=>{const span=spans.find(item=>item.id===id);if(span)select(span);}}>View exact source</button>)}</div></li>)}</ul></section>;
  if(view==="questions")return <section><h2>Open factual questions</h2><p className="lede">These questions identify missing evidence or unresolved conflicts. They are not legal advice.</p><JsonCards items={(data.questions??[]) as Json[]}/></section>;
  return <section><h2>{view[0].toUpperCase()+view.slice(1)}</h2><pre className="card" style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{JSON.stringify(data,null,2)}</pre></section>;
}
function JsonCards({items=[]}:{items?:Json[]}){return <ul className="list">{items.map((item,index)=><li className="card" key={String(item.id??index)}>{Object.entries(item).map(([key,value])=><p key={key}><strong>{key}:</strong> {typeof value==="object"?JSON.stringify(value):String(value)}</p>)}</li>)}</ul>}
