using System.Buffers;
using System.Security.Cryptography;
using CaseMesh.Core.Models;

namespace CaseMesh.Storage;

internal sealed class GeneratedArtifactStorageService : IGeneratedArtifactStore
{
    private const int BufferSize = 64 * 1024;
    private readonly IImmutableObjectBackend _backend;
    private readonly IGeneratedArtifactMetadataRepository _metadata;
    private readonly string _bucketName;
    private readonly TimeProvider _timeProvider;

    internal GeneratedArtifactStorageService(
        IImmutableObjectBackend backend,
        IGeneratedArtifactMetadataRepository metadata,
        string bucketName,
        TimeProvider timeProvider)
    {
        _backend = backend ?? throw new ArgumentNullException(nameof(backend));
        _metadata = metadata ?? throw new ArgumentNullException(nameof(metadata));
        ArgumentException.ThrowIfNullOrWhiteSpace(bucketName);
        _bucketName = bucketName;
        _timeProvider = timeProvider ?? throw new ArgumentNullException(nameof(timeProvider));
    }

    public async Task<StoredGeneratedArtifact> StoreAsync(
        GeneratedArtifactIdentity identity,
        Stream content,
        DateTimeOffset expiresAt,
        CancellationToken cancellationToken = default)
    {
        ValidateIdentity(identity);
        ArgumentNullException.ThrowIfNull(content);
        if (!content.CanRead) throw new ArgumentException("Generated content must be readable.", nameof(content));
        var now = _timeProvider.GetUtcNow();
        if (expiresAt <= now) throw new ArgumentOutOfRangeException(nameof(expiresAt));
        await using var lease = await _metadata.AcquireStoreLeaseAsync(identity, cancellationToken);
        var state = await _metadata.ResolveAsync(identity, cancellationToken)
            ?? throw new GeneratedArtifactNotFoundException("The immutable export artifact identity was not found.");
        await using var staged = await StagedArtifact.CreateAsync(content, cancellationToken);
        if (!string.Equals(staged.Sha256, state.ExpectedSha256, StringComparison.Ordinal) ||
            staged.ByteLength != state.ExpectedByteLength)
            throw new GeneratedArtifactIntegrityException("Generated bytes do not match immutable export audit metadata.");

        var address = Address(identity);
        var storage = state.Storage;
        if (storage is null)
        {
            storage = await _metadata.SaveAsync(new GeneratedArtifactStorageMetadata(
                identity, address, staged.Sha256, staged.ByteLength, now, expiresAt), cancellationToken);
        }
        RequireMatching(storage, address, staged.Sha256, staged.ByteLength);
        var create = await _backend.CreateIfAbsentAsync(address, staged.Stream, staged.ByteLength, cancellationToken);
        if (!create.Created) await VerifyPhysicalAsync(storage, cancellationToken);
        return storage.ToPublic();
    }

    public async Task<StoredGeneratedArtifact?> GetMetadataAsync(
        GeneratedArtifactIdentity identity,
        CancellationToken cancellationToken = default)
    {
        ValidateIdentity(identity);
        return (await _metadata.ResolveAsync(identity, cancellationToken))?.Storage?.ToPublic();
    }

    public async Task<StoredGeneratedArtifact> ReadVerifiedAsync(
        GeneratedArtifactIdentity identity,
        Stream destination,
        DateTimeOffset now,
        CancellationToken cancellationToken = default)
    {
        ValidateIdentity(identity);
        ArgumentNullException.ThrowIfNull(destination);
        if (!destination.CanWrite) throw new ArgumentException("Destination must be writable.", nameof(destination));
        var metadata = (await _metadata.ResolveAsync(identity, cancellationToken))?.Storage
            ?? throw new GeneratedArtifactNotFoundException("Generated artifact storage metadata was not found.");
        if (metadata.ExpiresAt <= now)
            throw new GeneratedArtifactExpiredException("The generated artifact retention window has expired.");
        await using var staged = await StagePhysicalAsync(metadata, cancellationToken);
        await staged.Stream.CopyToAsync(destination, BufferSize, cancellationToken);
        return metadata.ToPublic();
    }

    public async Task<bool> DeleteMatterAsync(TenantId tenantId, Guid matterId,
        CancellationToken cancellationToken = default)
    {
        RequireScope(tenantId, matterId);
        var records = await _metadata.ListMatterAsync(tenantId, matterId, cancellationToken);
        await DeletePhysicalAsync(records, cancellationToken);
        return records.Count == 0 || await _metadata.DeleteMetadataAsync(
            tenantId, records.Select(item => item.Identity).ToArray(), cancellationToken) == records.Count;
    }

    public async Task<bool> DeleteTenantAsync(TenantId tenantId, CancellationToken cancellationToken = default)
    {
        if (tenantId.Value == Guid.Empty) throw new ArgumentException("Tenant id is required.", nameof(tenantId));
        var records = await _metadata.ListTenantAsync(tenantId, cancellationToken);
        await DeletePhysicalAsync(records, cancellationToken);
        return records.Count == 0 || await _metadata.DeleteMetadataAsync(
            tenantId, records.Select(item => item.Identity).ToArray(), cancellationToken) == records.Count;
    }

    public async Task<int> DeleteExpiredAsync(TenantId tenantId, DateTimeOffset now,
        CancellationToken cancellationToken = default)
    {
        if (tenantId.Value == Guid.Empty) throw new ArgumentException("Tenant id is required.", nameof(tenantId));
        var records = await _metadata.ListExpiredAsync(tenantId, now, cancellationToken);
        await DeletePhysicalAsync(records, cancellationToken);
        return records.Count == 0 ? 0 : await _metadata.DeleteMetadataAsync(
            tenantId, records.Select(item => item.Identity).ToArray(), cancellationToken);
    }

    public async Task<bool> CheckReadinessAsync(CancellationToken cancellationToken = default)
    {
        try
        {
            var probe = new StorageAddress("s3", _bucketName, "v1/readiness-probe-do-not-create");
            await using var ignored = await _backend.OpenReadAsync(probe, cancellationToken);
            return true;
        }
        catch (OriginalEvidenceNotFoundException)
        {
            return true;
        }
        catch
        {
            return false;
        }
    }

    public ValueTask DisposeAsync() => ValueTask.CompletedTask;

    private async Task DeletePhysicalAsync(
        IReadOnlyList<GeneratedArtifactStorageMetadata> records,
        CancellationToken cancellationToken)
    {
        foreach (var record in records)
            await _backend.DeleteIfExistsAsync(record.Address, cancellationToken);
    }

    private async Task VerifyPhysicalAsync(
        GeneratedArtifactStorageMetadata metadata,
        CancellationToken cancellationToken)
    {
        await using var ignored = await StagePhysicalAsync(metadata, cancellationToken);
    }

    private async Task<StagedArtifact> StagePhysicalAsync(
        GeneratedArtifactStorageMetadata metadata,
        CancellationToken cancellationToken)
    {
        Stream source;
        try { source = await _backend.OpenReadAsync(metadata.Address, cancellationToken); }
        catch (OriginalEvidenceNotFoundException exception)
        { throw new GeneratedArtifactNotFoundException(exception.Message); }
        catch (Exception exception) when (exception is not OperationCanceledException)
        { throw new GeneratedArtifactAvailabilityException("Generated artifact storage is unavailable.", exception); }
        await using (source)
        {
            var staged = await StagedArtifact.CreateAsync(source, cancellationToken);
            if (!string.Equals(staged.Sha256, metadata.ContentSha256, StringComparison.Ordinal) ||
                staged.ByteLength != metadata.ByteLength)
            {
                await staged.DisposeAsync();
                throw new GeneratedArtifactIntegrityException("Generated artifact bytes failed SHA-256 or length verification.");
            }
            return staged;
        }
    }

    private StorageAddress Address(GeneratedArtifactIdentity identity) => new(
        "s3", _bucketName,
        $"v1/tenants/{identity.TenantId.Value:D}/matters/{identity.MatterId:D}/generated/exports/{identity.ExportId:D}/{identity.ArtifactKind}");

    private static void RequireMatching(GeneratedArtifactStorageMetadata metadata, StorageAddress address,
        string sha256, long byteLength)
    {
        if (metadata.Address != address || metadata.ContentSha256 != sha256 || metadata.ByteLength != byteLength)
            throw new GeneratedArtifactConflictException("Generated artifact identity cannot be rebound to different bytes or storage.");
    }

    private static void ValidateIdentity(GeneratedArtifactIdentity identity)
    {
        ArgumentNullException.ThrowIfNull(identity);
        RequireScope(identity.TenantId, identity.MatterId);
        if (identity.ExportId == Guid.Empty || identity.ArtifactKind is < 0 or > 7)
            throw new ArgumentException("A complete typed generated artifact identity is required.", nameof(identity));
    }

    private static void RequireScope(TenantId tenantId, Guid matterId)
    {
        if (tenantId.Value == Guid.Empty || matterId == Guid.Empty)
            throw new ArgumentException("Tenant and Matter identities are required.");
    }

    private sealed class StagedArtifact : IAsyncDisposable
    {
        private readonly string _path;
        internal FileStream Stream { get; }
        internal string Sha256 { get; }
        internal long ByteLength { get; }

        private StagedArtifact(string path, FileStream stream, string sha256, long byteLength)
        { _path = path; Stream = stream; Sha256 = sha256; ByteLength = byteLength; }

        internal static async Task<StagedArtifact> CreateAsync(Stream source, CancellationToken cancellationToken)
        {
            var path = Path.Combine(Path.GetTempPath(), $"casemesh-generated-{Guid.NewGuid():N}.tmp");
            FileStream? stream = null;
            try
            {
                var options = new FileStreamOptions
                {
                    Mode = FileMode.CreateNew,
                    Access = FileAccess.ReadWrite,
                    Share = FileShare.None,
                    BufferSize = BufferSize,
                    Options = FileOptions.Asynchronous | FileOptions.SequentialScan
                };
                if (!OperatingSystem.IsWindows()) options.UnixCreateMode = UnixFileMode.UserRead | UnixFileMode.UserWrite;
                stream = new FileStream(path, options);
                using var hash = IncrementalHash.CreateHash(HashAlgorithmName.SHA256);
                var buffer = ArrayPool<byte>.Shared.Rent(BufferSize);
                long length = 0;
                try
                {
                    int read;
                    while ((read = await source.ReadAsync(buffer.AsMemory(0, BufferSize), cancellationToken)) > 0)
                    {
                        length = checked(length + read);
                        hash.AppendData(buffer, 0, read);
                        await stream.WriteAsync(buffer.AsMemory(0, read), cancellationToken);
                    }
                }
                finally { ArrayPool<byte>.Shared.Return(buffer, clearArray: true); }
                await stream.FlushAsync(cancellationToken);
                stream.Position = 0;
                return new StagedArtifact(path, stream, Convert.ToHexString(hash.GetHashAndReset()), length);
            }
            catch
            {
                if (stream is not null) await stream.DisposeAsync();
                try { File.Delete(path); } catch (IOException) { } catch (UnauthorizedAccessException) { }
                throw;
            }
        }

        public async ValueTask DisposeAsync()
        {
            await Stream.DisposeAsync();
            try { File.Delete(_path); } catch (IOException) { } catch (UnauthorizedAccessException) { }
        }
    }
}
